#!/bin/zsh

if [ -z "$!" ] ; then
    echo usage: $0 SECRET_NAME
fi

kubectl get secret -o go-template='{{range $k,$v := .data}}{{printf "%s: " $k}}{{if not $v}}{{$v}}{{else}}{{$v | base64decode}}{{end}}{{"\n"}}{{end}}' $*
