#!/bin/zsh

function pwgen_ansible {
    LEN=${1:-8}
    shift
    PARAMS=${@:-"-B"}
    password=$(pwgen $PARAMS $LEN)
    echo Password: $password
    echo
    echo $password | ansible-vault encrypt_string --vault-id @vault_id.sh
}
