#!/bin/zsh

[ -z "$1" ] && {
  echo "usage: $0 <git-url>"
  return 1
}

repo_url="$1"

case "$repo_url" in
  git@*:* )
    target_dir="${repo_url#*:}"
    ;;
  http://* | https://* )
    target_dir="${repo_url#*://*/}"
    ;;
  * )
    target_dir="$repo_url"
    ;;
esac

target_dir="${target_dir%.git}"
target_dir="${target_dir#/}"

echo "Cloning into $target_dir..."
takedir "$target_dir"
git clone "$repo_url" .
