#!/bin/zsh

typeset -A sessions

sessions=(
    'sshuttle' '~'
)

session=$1
session_path=$2

if [ -z "$session" ] ; then
    echo usage $0 SESSION_NAME
    return
fi

if tmux has-session -t "=$session" ; then
    [ -z "$TMUX" ] && tmux attach-session -t "=$session"
    [ ! -z "$TMUX" ] && tmux switch-client -t "=$session"
    return
fi


if [ -z "$session_path" ] ;  then
    session_path=$sessions[$session]
    if [ -z "$session_path" ] ;  then
        if [ -d "$HOME/git/$session" ] ; then
            session_path="$HOME/git/$session"
        else
            session_path="$HOME"
        fi
    fi
fi

tmux new-session -s "$session" -c "$session_path" -d
[ -z "$TMUX" ] && tmux attach-session -t $session
[ ! -z "$TMUX" ] && tmux switch-client -t $session
